language: node_js
node_js:
  - "0.12"
before_script:
  - "npm install"
  - "npm install -g karma"
  - "npm install -g karma-cli"
  - "npm install karma-jasmine"
  - "npm install karma-chrome-launcher"
deploy:
  provider: heroku
  api_key: "d3f03084-a164-429f-8a6a-ed5611e436ce"
  app: bmeautsoft-travis-nodejs-test